application.version=@appVersion@
#debug=true
server.port=8000
server.tomcat.max-threads=10
#server.tomcat.max-connections=100000

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/master.xml
spring.liquibase.enabled=true

spring.datasource.hikari.maximum-pool-size=5

# Database settings - PROD
spring.datasource.url=${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
